# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  invenio_bundled.yaml
#   timestamp: 2026-08-27T12:29:28+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Version(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    index: int | None = None
    is_latest: bool | None = None
    is_latest_draft: bool | None = None


class PID(BaseModel):
    """
    An external persistent identifier object.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    identifier: str
    """
    An identifier.
    """
    provider: str
    """
    The provider of the persistent identifier.
    """
    client: str | None = None
    """
    Client identifier for the specific PID.
    """


class Redirect(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    status: Literal[301] = 301
    message: str
    location: AnyUrl


class Status(Enum):
    DRAFT = "draft"
    PUBLISHED = "published"


class State(Enum):
    UNSUBMITTED = "unsubmitted"
    DONE = "done"
    INPROGRESS = "inprogress"


class ZenodoFile(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str | None = None
    key: str | None = None
    size: int | None = None
    checksum: str | None = None
    links: dict[str, AnyUrl] | None = None


class ZenodoOwner(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str


class FileTransferType(Enum):
    """
    The actual technology that is used to store a file
    """

    L = "L"
    F = "F"
    M = "M"
    R = "R"


class FileTransfer(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: FileTransferType | None = None
    url: AnyUrl | None = None
    """
    URL to fetch the file from
    """


class FileTransferItem(BaseModel):
    """
    A file object.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    key: str
    """
    Key (filename) of the file
    """
    size: int | None = None
    """
    Size of the file in bytes.
    """
    checksum: str | None = None
    """
    Checksum of the file.
    """
    transfer: FileTransfer | None = None


class Embargo(BaseModel):
    """
    Only in the cases of `"record": "restricted"`` or `"files": "restricted"`` can an embargo be provided as input.
    However, once an embargo is lifted, the embargo section is kept for transparency.

    Denotes when an embargo must be lifted, at which point the record is made publicly accessible.

    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    active: bool | None = None
    """
    Is the record under embargo or not.
    """
    until: date_aliased | None = None
    """
    Required if `"active": "true"`.

    """
    reason: str | None = None
    """
    Explanation for the embargo.
    """


class AccessRecord(Enum):
    """
    Read access to the record.

    `public` means anyone can see the record/files, `restricted` means only the owner(s) or specific users can see the record/files.

    """

    PUBLIC = "public"
    RESTRICTED = "restricted"


class AccessFiles(Enum):
    """
    Read access to the record's files.

    `public` means anyone can see the record/files, `restricted` means only the owner(s) or specific users can see the record/files.

    """

    PUBLIC = "public"
    RESTRICTED = "restricted"


class Access(BaseModel):
    """
    Denotes record-specific read (visibility) options.

    More informations can be found on InvenioRDM Official page: https://inveniordm.docs.cern.ch/reference/metadata/#access

    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    record: AccessRecord
    files: AccessFiles
    embargo: Embargo | None = None
    status: str | None = None
    """
    Access status.
    """


class File(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str | None = None
    checksum: str | None = None
    ext: str | None = None
    size: int | None = None
    mimetype: str | None = None
    storage_class: str | None = None
    key: str | None = None
    metadata: dict[str, Any] | None = None
    access: dict[str, Any] | None = None
    processor: dict[str, Any] | None = None


class ResourceTypeId(Enum):
    """
    The resource type id from the controlled vocabulary.
    """

    PUBLICATION = "publication"
    PUBLICATION_ANNOTATIONCOLLECTION = "publication-annotationcollection"
    PUBLICATION_BOOK = "publication-book"
    PUBLICATION_SECTION = "publication-section"
    PUBLICATION_CONFERENCEPAPER = "publication-conferencepaper"
    PUBLICATION_CONFERENCEPROCEEDING = "publication-conferenceproceeding"
    PUBLICATION_DATAMANAGEMENTPLAN = "publication-datamanagementplan"
    PUBLICATION_JOURNAL = "publication-journal"
    PUBLICATION_ARTICLE = "publication-article"
    PUBLICATION_PATENT = "publication-patent"
    PUBLICATION_PEERREVIEW = "publication-peerreview"
    PUBLICATION_PREPRINT = "publication-preprint"
    PUBLICATION_DELIVERABLE = "publication-deliverable"
    PUBLICATION_MILESTONE = "publication-milestone"
    PUBLICATION_PROPOSAL = "publication-proposal"
    PUBLICATION_REPORT = "publication-report"
    PUBLICATION_SOFTWAREDOCUMENTATION = "publication-softwaredocumentation"
    PUBLICATION_TAXONOMICTREATMENT = "publication-taxonomictreatment"
    PUBLICATION_TECHNICALNOTE = "publication-technicalnote"
    PUBLICATION_THESIS = "publication-thesis"
    PUBLICATION_WORKINGPAPER = "publication-workingpaper"
    PUBLICATION_DATAPAPER = "publication-datapaper"
    PUBLICATION_DISSERTATION = "publication-dissertation"
    PUBLICATION_STANDARD = "publication-standard"
    PUBLICATION_OTHER = "publication-other"
    POSTER = "poster"
    PRESENTATION = "presentation"
    EVENT = "event"
    DATASET = "dataset"
    IMAGE = "image"
    IMAGE_FIGURE = "image-figure"
    IMAGE_PLOT = "image-plot"
    IMAGE_DRAWING = "image-drawing"
    IMAGE_DIAGRAM = "image-diagram"
    IMAGE_PHOTO = "image-photo"
    IMAGE_OTHER = "image-other"
    MODEL = "model"
    VIDEO = "video"
    AUDIO = "audio"
    SOFTWARE = "software"
    LESSON = "lesson"
    SOFTWARE_COMPUTATIONALNOTEBOOK = "software-computationalnotebook"
    OTHER = "other"
    PHYSICALOBJECT = "physicalobject"
    WORKFLOW = "workflow"


class ResourceType(BaseModel):
    """
    The type of the resource described by the record.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: ResourceTypeId


class PersonOrOrgIdentifierScheme(Enum):
    """
    The identifier scheme.

    Note that the identifiers' schemes are passed lowercased e.g. ORCID is `orcid`.

    """

    ORCID = "orcid"
    GND = "gnd"
    ISNI = "isni"
    ROR = "ror"


class Identifier(BaseModel):
    """
    Person or organisation identifier.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    scheme: PersonOrOrgIdentifierScheme
    identifier: str
    """
    Actual value of the identifier.
    """


class PersonOrOrgType(Enum):
    """
    The type of name.
    """

    PERSONAL = "personal"
    ORGANIZATIONAL = "organizational"


class PersonOrOrg(BaseModel):
    """
    The person or organization.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: PersonOrOrgType
    given_name: str | None = None
    """
    Given name(s).
    """
    family_name: str | None = None
    """
    Family name.
    """
    name: str | None = None
    """
    The full name of the organisation.

    For a person, this field is generated from `given_name` and `family_name`.

    """
    identifiers: list[Identifier] | None = None
    """
    Person or organisation identifiers.
    """


class RoleId(Enum):
    """
    The role's controlled vocabulary identifier.
    """

    CONTACTPERSON = "contactperson"
    DATACOLLECTOR = "datacollector"
    DATACURATOR = "datacurator"
    DATAMANAGER = "datamanager"
    DISTRIBUTOR = "distributor"
    EDITOR = "editor"
    HOSTINGINSTITUTION = "hostinginstitution"
    PRODUCER = "producer"
    PROJECTLEADER = "projectleader"
    PROJECTMANAGER = "projectmanager"
    PROJECTMEMBER = "projectmember"
    REGISTRATIONAGENCY = "registrationagency"
    REGISTRATIONAUTHORITY = "registrationauthority"
    RELATEDPERSON = "relatedperson"
    RESEARCHER = "researcher"
    RESEARCHGROUP = "researchgroup"
    RIGHTSHOLDER = "rightsholder"
    SPONSOR = "sponsor"
    SUPERVISOR = "supervisor"
    WORKPACKAGELEADER = "workpackageleader"
    OTHER = "other"


class Role(BaseModel):
    """
    The role of the person or organisation selected from a customizable controlled vocabulary.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: RoleId


class Affiliation(BaseModel):
    """
    Affilations if `person_or_org.type` is `personal`.

    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str | None = None
    """
    The organizational or institutional id from the controlled vocabulary.
    """
    name: str | None = None
    """
    The name of the organisation or institution.
    """


class Creator(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    person_or_org: PersonOrOrg
    role: Role | None = None
    affiliations: list[Affiliation] | None = None
    """
    Affilations if `person_or_org.type` is personal.

    """


class Contributor(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    person_or_org: PersonOrOrg
    role: Role
    affiliations: list[Affiliation] | None = None


class AdditionalTitleTypeId(Enum):
    """
    Title type id from the controlled vocabulary.
    """

    ALTERNATIVE_TITLE = "alternative-title"
    SUBTITLE = "subtitle"
    TRANSLATED_TITLE = "translated-title"
    OTHER = "other"


class AdditionalTitleType(BaseModel):
    """
    The type of the title.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: AdditionalTitleTypeId
    title: dict[str, Any] | None = None
    """
    The corresponding localized human readable label
    """


class Lang(BaseModel):
    """
    The language of the associated item.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str
    """
    The ISO-639-3 language code.
    """


class AdditionalTitle(BaseModel):
    """
    Additional name or title by which a resource is known.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    title: str
    """
    The additional title.
    """
    type: AdditionalTitleType
    lang: Lang | None = None


class AdditionalDescriptionTypeId(Enum):
    """
    Description type id from the controlled vocabulary
    """

    ABSTRACT = "abstract"
    METHODS = "methods"
    SERIES_INFORMATION = "series-information"
    TABLE_OF_CONTENTS = "table-of-contents"
    TECHNICAL_INFO = "technical-info"
    OTHER = "other"


class AdditionalDescriptionType(BaseModel):
    """
    The type of the description.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: AdditionalDescriptionTypeId
    title: dict[str, Any] | None = None
    """
    The corresponding localized human readable label.
    """


class AdditionalDescription(BaseModel):
    """
    Additional description in addition to the primary description (e.g. abstracts in other languages), methods or further notes.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    description: str
    """
    Free text.
    """
    type: AdditionalDescriptionType
    lang: Lang | None = None


class Right(BaseModel):
    """
    Right management statement for the resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str | None = None
    """
    Identifier value.
    """
    title: dict[str, Any] | None = None
    """
    Localized human readable title.
    """
    description: dict[str, Any] | None = None
    """
    Localized license description text
    """
    icon: str | None = None
    """
    License icon.
    """
    props: dict[str, Any] | None = None
    link: AnyUrl | None = None
    """
    Link to the full license.
    """


class Subject(BaseModel):
    """
    Subject, keyword, classification code, or key phrase describing the resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str | None = None
    """
    The identifier of the subject from the controlled vocabulary.
    """
    subject: str | None = None
    """
    A custom keyword.
    """


class DateTypeId(Enum):
    """
    Date type id from the controlled vocabulary
    """

    ACCEPTED = "accepted"
    AVAILABLE = "available"
    COLLECTED = "collected"
    COPYRIGHTED = "copyrighted"
    CREATED = "created"
    ISSUED = "issued"
    OTHER = "other"
    SUBMITTED = "submitted"
    UPDATED = "updated"
    VALID = "valid"
    WITHDRAWN = "withdrawn"


class DateType(BaseModel):
    """
    The type of date.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: DateTypeId
    title: dict[str, Any] | None = None
    """
    The corresponding localized human readable label
    """


class Date(BaseModel):
    """
    Date relevant to the resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    date: str
    """
    A date or time interval according to Extended Date Time Format Level 0.
    """
    type: DateType
    description: str | None = None


class IdentifierScheme(Enum):
    """
    The scheme of the identifier
    """

    ARK = "ark"
    ARXIV = "arxiv"
    ADS = "ads"
    CROSSREFFUNDERID = "crossreffunderid"
    DOI = "doi"
    EAN13 = "ean13"
    EISSN = "eissn"
    GRID = "grid"
    HANDLE = "handle"
    IGSN = "igsn"
    ISBN = "isbn"
    ISNI = "isni"
    ISSN = "issn"
    ISTC = "istc"
    LISSN = "lissn"
    LSID = "lsid"
    PMID = "pmid"
    PURL = "purl"
    UPC = "upc"
    URL = "url"
    URN = "urn"
    W3ID = "w3id"
    OTHER = "other"


class AlternateIdentifier(BaseModel):
    """
    Persistent identifier for the resource other than the ones registered as system-managed internal or external persistent identifiers.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    identifier: str
    """
    identifier value
    """
    scheme: IdentifierScheme


class RelationTypeId(Enum):
    """
    Relation type id from the controlled vocabulary
    """

    ISCITEDBY = "iscitedby"
    CITES = "cites"
    ISSUPPLEMENTTO = "issupplementto"
    ISSUPPLEMENTEDBY = "issupplementedby"
    ISCONTINUEDBY = "iscontinuedby"
    CONTINUES = "continues"
    ISDESCRIBEDBY = "isdescribedby"
    DESCRIBES = "describes"
    HASMETADATA = "hasmetadata"
    ISMETADATAFOR = "ismetadatafor"
    HASVERSION = "hasversion"
    ISVERSIONOF = "isversionof"
    ISNEWVERSIONOF = "isnewversionof"
    ISPREVIOUSVERSIONOF = "ispreviousversionof"
    ISPARTOF = "ispartof"
    HASPART = "haspart"
    ISPUBLISHEDIN = "ispublishedin"
    ISREFERENCEDBY = "isreferencedby"
    REFERENCES = "references"
    ISDOCUMENTEDBY = "isdocumentedby"
    DOCUMENTS = "documents"
    ISCOMPILEDBY = "iscompiledby"
    COMPILES = "compiles"
    ISVARIANTFORMOF = "isvariantformof"
    ISORIGINALFORMOF = "isoriginalformof"
    ISIDENTICALTO = "isidenticalto"
    ISREVIEWEDBY = "isreviewedby"
    REVIEWS = "reviews"
    ISDERIVEDFROM = "isderivedfrom"
    ISSOURCEOF = "issourceof"
    ISREQUIREDBY = "isrequiredby"
    REQUIRES = "requires"
    ISOBSOLETEDBY = "isobsoletedby"
    OBSOLETES = "obsoletes"


class RelationType(BaseModel):
    """
    The relation of the record to this related resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: RelationTypeId
    title: dict[str, Any] | None = None
    """
    The corresponding localized human readable label
    """


class RelatedIdentifierResourceTypeId(Enum):
    """
    Date type id from the controlled vocabulary.
    """

    PUBLICATION = "publication"
    PUBLICATION_ANNOTATIONCOLLECTION = "publication-annotationcollection"
    PUBLICATION_BOOK = "publication-book"
    PUBLICATION_SECTION = "publication-section"
    PUBLICATION_CONFERENCEPAPER = "publication-conferencepaper"
    PUBLICATION_CONFERENCEPROCEEDING = "publication-conferenceproceeding"
    PUBLICATION_DATAMANAGEMENTPLAN = "publication-datamanagementplan"
    PUBLICATION_JOURNAL = "publication-journal"
    PUBLICATION_ARTICLE = "publication-article"
    PUBLICATION_PATENT = "publication-patent"
    PUBLICATION_PEERREVIEW = "publication-peerreview"
    PUBLICATION_PREPRINT = "publication-preprint"
    PUBLICATION_DELIVERABLE = "publication-deliverable"
    PUBLICATION_MILESTONE = "publication-milestone"
    PUBLICATION_PROPOSAL = "publication-proposal"
    PUBLICATION_REPORT = "publication-report"
    PUBLICATION_SOFTWAREDOCUMENTATION = "publication-softwaredocumentation"
    PUBLICATION_TAXONOMICTREATMENT = "publication-taxonomictreatment"
    PUBLICATION_TECHNICALNOTE = "publication-technicalnote"
    PUBLICATION_THESIS = "publication-thesis"
    PUBLICATION_WORKINGPAPER = "publication-workingpaper"
    PUBLICATION_DATAPAPER = "publication-datapaper"
    PUBLICATION_DISSERTATION = "publication-dissertation"
    PUBLICATION_STANDARD = "publication-standard"
    PUBLICATION_OTHER = "publication-other"
    POSTER = "poster"
    PRESENTATION = "presentation"
    EVENT = "event"
    DATASET = "dataset"
    IMAGE = "image"
    IMAGE_FIGURE = "image-figure"
    IMAGE_PLOT = "image-plot"
    IMAGE_DRAWING = "image-drawing"
    IMAGE_DIAGRAM = "image-diagram"
    IMAGE_PHOTO = "image-photo"
    IMAGE_OTHER = "image-other"
    MODEL = "model"
    VIDEO = "video"
    AUDIO = "audio"
    SOFTWARE = "software"
    LESSON = "lesson"
    SOFTWARE_COMPUTATIONALNOTEBOOK = "software-computationalnotebook"
    OTHER = "other"
    PHYSICALOBJECT = "physicalobject"
    WORKFLOW = "workflow"


class RelatedIdentifierResourceType(BaseModel):
    """
    The resource type of the related resource
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: RelatedIdentifierResourceTypeId
    title: dict[str, Any] | None = None
    """
    The corresponding localized human readable label
    """


class RelatedIdentifier(BaseModel):
    """
    Identifier of related resources.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    identifier: str
    """
    A global unique persistent identifier for a related resource.
    """
    scheme: IdentifierScheme
    relation_type: RelationType
    resource_type: RelatedIdentifierResourceType | None = None


class FeatureIdentifier(BaseModel):
    """
    A geographic location identifier.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str
    """
    A globally unique identifier for the location.
    """
    scheme: str | None = None
    """
    The scheme of the identifier.
    """


class Funder(BaseModel):
    """
    The organisation of the funding provider.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str | None = None
    """
    The funder id from the controlled vocabulary.
    """
    name: str | None = None
    """
    The name of the funder.
    """


class AwardIdentifier(BaseModel):
    """
    Identifier for the award.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    scheme: str
    """
    The identifier scheme.
    """
    identifier: str
    """
    Actual value of the identifier.
    """


class Award(BaseModel):
    """
    The award (grant) sponsored by the funder.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str | None = None
    """
    The award id from the controlled vocabulary.
    """
    title: dict[str, Any] | None = None
    """
    The localized title of the award.
    """
    number: str | None = None
    """
    The code assigned by the funder to a sponsored award (grant).
    """
    identifiers: list[AwardIdentifier] | None = None
    """
    Identifiers for the award.
    """


class Funding(BaseModel):
    """
    Information about financial support (funding) for the resource being registered.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    funder: Funder
    award: Award | None = None


class Reference(BaseModel):
    """
    Reference string.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    reference: str
    """
    The full reference string.
    """
    scheme: IdentifierScheme | None = None
    identifier: str | None = None
    """
    The identifier if known.
    """


class CustomFields(BaseModel):
    """
    Custom fields metadata for the record. (v10 and newer).

    More informations can be found on InvenioRDM Official page: https://inveniordm.docs.cern.ch/operate/customize/metadata/custom_fields/records/#declaring-custom-fields

    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )


class Resource(BaseModel):
    """
    Resource affected by the action
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Annotated[str | None, Field(examples=["record"])] = None
    """
    Type of the resource
    """
    id: Annotated[str | None, Field(examples=["5anb0-85626"])] = None
    """
    ID of the resource
    """


class Metadata1(BaseModel):
    """
    Additional metadata about the log entry
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    ip_address: str | None = None
    """
    IP address from which the action was performed
    """
    session: str | None = None
    """
    Session identifier
    """
    parent_pid: Annotated[str | None, Field(examples=["1av3p-t2p41"])] = None
    """
    Parent persistent identifier
    """
    revision_id: Annotated[int | None, Field(examples=[110])] = None
    """
    Revision ID of the resource
    """


class User(BaseModel):
    """
    User who performed the action
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[str | None, Field(examples=["2"])] = None
    """
    User ID
    """
    username: Annotated[str | None, Field(examples=["user"])] = None
    """
    Username
    """
    email: Annotated[str | None, Field(examples=["user@demo.org"])] = None
    """
    User email address
    """


class Links(BaseModel):
    """
    Links related to the log entry
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    self: Annotated[
        str | None,
        Field(
            examples=[
                "https://example.com/api/audit-logs/9913abd2-1a7c-42cb-a73e-e48a9e1bf4f2"
            ]
        ),
    ] = None
    """
    Self link to the log entry
    """


class AuditLogEntry(BaseModel):
    """
    Conflict - Resource already exists or operation conflicts
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[
        str | None, Field(examples=["9913abd2-1a7c-42cb-a73e-e48a9e1bf4f2"])
    ] = None
    """
    Unique identifier for the log entry
    """
    created: Annotated[
        AwareDatetime | None, Field(examples=["2025-06-20T08:05:27.730677+00:00"])
    ] = None
    """
    Timestamp when the log entry was created
    """
    action: Annotated[str | None, Field(examples=["record.publish"])] = None
    """
    Action performed
    """
    resource: Resource | None = None
    """
    Resource affected by the action
    """
    metadata: Metadata1 | None = None
    """
    Additional metadata about the log entry
    """
    user: User | None = None
    """
    User who performed the action
    """
    links: Links | None = None
    """
    Links related to the log entry
    """


class Type(Enum):
    POINT = "Point"


class Geometry1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Type
    coordinates: Annotated[list[float], Field(min_length=2)]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None


class Type1(Enum):
    LINE_STRING = "LineString"


class Coordinate(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class Geometry2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Type1
    coordinates: Annotated[list[Coordinate], Field(min_length=2)]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None


class Type2(Enum):
    POLYGON = "Polygon"


class Coordinate1Item(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class Coordinate1(RootModel[list[Coordinate1Item]]):
    root: Annotated[list[Coordinate1Item], Field(min_length=4)]


class Geometry3(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Type2
    coordinates: list[Coordinate1]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None


class Type3(Enum):
    MULTI_POINT = "MultiPoint"


class Coordinate2(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class Geometry4(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Type3
    coordinates: list[Coordinate2]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None


class Type4(Enum):
    MULTI_LINE_STRING = "MultiLineString"


class Coordinate3Item(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class Coordinate3(RootModel[list[Coordinate3Item]]):
    root: Annotated[list[Coordinate3Item], Field(min_length=2)]


class Geometry5(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Type4
    coordinates: list[Coordinate3]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None


class Type5(Enum):
    MULTI_POLYGON = "MultiPolygon"


class Coordinate4Item(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class Coordinate4(RootModel[list[Coordinate4Item]]):
    root: Annotated[list[Coordinate4Item], Field(min_length=4)]


class Geometry6(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Type5
    coordinates: list[list[Coordinate4]]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None


class ZenodoRecord(BaseModel):
    """
    Zenodo application/json representation for records and drafts. Zenodo
    overrides InvenioRDM's default record serializer with its Zenodo v1
    compatibility serializer; notably, id is numeric and files is an array.

    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    created: AwareDatetime | None = None
    modified: AwareDatetime | None = None
    updated: AwareDatetime | None = None
    id: int
    conceptrecid: str | None = None
    recid: str | None = None
    revision: int | None = None
    doi: str | None = None
    conceptdoi: str | None = None
    doi_url: AnyUrl | None = None
    metadata: dict[str, Any] | None = None
    title: str | None = None
    links: dict[str, AnyUrl] | None = None
    files: list[ZenodoFile] | None = None
    owners: list[ZenodoOwner] | None = None
    status: Status | None = None
    state: State | None = None
    submitted: bool | None = None
    stats: dict[str, Any] | None = None
    swh: dict[str, Any] | None = None


class Files(BaseModel):
    """
    Files options for the record.

    More informations can be found on InvenioRDM Official page: https://inveniordm.docs.cern.ch/reference/rest_api_drafts_records/#files-options

    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    enabled: bool | None = None
    """
    Should (and can) files be attached to this record or not.
    """
    default_preview: str | None = None
    """
    Filename of file to be previewed by default.
    """
    order: list[str] | None = None
    """
    Array of filename strings in display order.
    """
    count: int | None = None
    """
    Number of files.
    """
    total_bytes: int | None = None
    """
    Total size of all files in bytes.
    """
    entries: dict[str, File] | None = None
    """
    Files keyed by filename.
    """


class Feature(BaseModel):
    """
    A GeoJSON feature object.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    geometry: Annotated[
        Geometry1 | Geometry2 | Geometry3 | Geometry4 | Geometry5 | Geometry6 | None,
        Field(title="GeoJSON Geometry"),
    ] = None
    """
    A GeoJSON Geometry Object according to RFC 7946
    """
    identifiers: list[FeatureIdentifier] | None = None
    """
    A list of geographic location identifiers.
    """
    place: str | None = None
    """
    Free text, used to describe a geographical location.
    """
    description: str | None = None
    """
    Free text, used for any extra information related to the location.
    """


class Location(BaseModel):
    """
    Spatial region or named place where the data was gathered or about which the data is focused.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    features: list[Feature]
    """
    A list of GeoJSON feature objects.
    """


class Metadata(BaseModel):
    """
    Metadata schema of bibliographic records in InvenioRDM.

    More informations can be found on InvenioRDM Official page: https://inveniordm.docs.cern.ch/reference/metadata/#metadata

    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    resource_type: ResourceType | None = None
    title: str | None = None
    """
    A primary name or primary title by which a resource is known.
    """
    publication_date: str | None = None
    """
    The date when the resource was or will be made publicly available.
    """
    creators: Annotated[list[Creator] | None, Field(min_length=1)] = None
    """
    The creators field registers those persons or organisations that should be credited for the resource described by the record.
    """
    additional_titles: list[AdditionalTitle] | None = None
    """
    Additional names or titles by which a resource is known
    """
    description: str | None = None
    """
    The description of a record.
    """
    additional_descriptions: list[AdditionalDescription] | None = None
    """
    Additional descriptions in addition to the primary description (e.g. abstracts in other languages), methods or further notes.
    """
    rights: list[Right] | None = None
    """
    Rights management statement for the resource.
    """
    copyright: str | None = None
    """
    The copyright field allows authors or depositors to specify a copyright statement for the record.
    """
    contributors: list[Contributor] | None = None
    """
    The organisations or persons responsible for collecting, managing, distributing, or otherwise contributing to the development of the resource.
    """
    subjects: list[Subject] | None = None
    """
    Subject, keyword, classification code, or key phrase describing the resource.
    """
    languages: list[Lang] | None = None
    """
    The languages of the resource.
    """
    dates: list[Date] | None = None
    """
    Different dates relevant to the resource.
    """
    version: str | None = None
    """
    The version number of the resource.
    """
    publisher: str | None = None
    """
    The name of the entity that holds, archives, publishes, prints, distributes, releases, issues, or produces the resource.
    """
    identifiers: list[AlternateIdentifier] | None = None
    """
    Persistent identifiers for the resource other than the ones registered as system-managed internal or external persistent identifiers.
    """
    related_identifiers: list[RelatedIdentifier] | None = None
    """
    Identifiers of related resources.
    """
    sizes: list[str] | None = None
    """
    Size (e.g. bytes, pages, inches, etc.) or duration (extent), e.g. hours, minutes, days, etc., of a resource.
    """
    formats: list[str] | None = None
    """
    Technical format of the resource.
    """
    locations: Location | None = None
    """
    Spatial region or named place where the data was gathered or about which the data is focused.
    """
    funding: list[Funding] | None = None
    """
    Information about financial support (funding) for the resource being registered.
    """
    references: list[Reference] | None = None
    """
    A list of reference strings.
    """


class UpdateDraftRecord(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    access: Access | None = None
    files: Files | None = None
    metadata: Metadata | None = None
    custom_fields: CustomFields | None = None


class Hits(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    total: int | None = None
    """
    Total number of log entries
    """
    hits: list[AuditLogEntry] | None = None


class AuditLogList(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    hits: Hits | None = None
    aggregations: dict[str, Any] | None = None
    """
    Aggregation results (if any)
    """


class CreateADraftRecordBody(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    access: Access | None = None
    files: Files | None = None
    metadata: Metadata | None = None
    custom_fields: dict[str, Any] | None = None
    pids: dict[str, PID] | None = None


class RDMRecord(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    access: Access | None = None
    created: AwareDatetime | None = None
    expires_at: AwareDatetime | None = None
    files: Files | None = None
    media_files: Files | None = None
    id: str
    is_published: bool | None = None
    is_draft: bool | None = None
    links: dict[str, AnyUrl] | None = None
    metadata: Metadata | None = None
    custom_fields: CustomFields | None = None
    parent: dict[str, Any] | None = None
    pids: dict[str, PID] | None = None
    revision_id: int | None = None
    revision: int | None = None
    status: str | None = None
    updated: AwareDatetime | None = None
    versions: Version | None = None


class RecordResponse(RootModel[RDMRecord | ZenodoRecord]):
    root: RDMRecord | ZenodoRecord
    """
    Record representation returned by an InvenioRDM instance.

    Vanilla InvenioRDM serializes records using RDMRecordSchema. Zenodo
    intentionally overrides the application/json record serializer with
    its Zenodo v1 compatibility representation, so both representations
    are valid responses from an InvenioRDM-compatible deployment.

    """
